select = ["ALL"]
ignore = [
	"E501",
	"E701",
	"E702",
	"E741",
	"E401",
	"D100",
	"D101",
	"D102",
	"D103",
	"D105",
	"D107",
	"D203",
	"D211",
	"D212",
	"D213",
	"S101",
	"I001",
	"Q003",
	"T201",
	"PYI034",
	"W292",
	"TD002",
	"TD003",
	"PT018",
	"PT027",
	"ANN",
	"COM812",
	"PLR2004",
	"PLR0912",
	"PLR0913",
	"ERA001",
	"FBT001",
	"FBT002",
	"BLE001"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
	".bzr",
	".direnv",
	".eggs",
	".git",
	".git-rewrite",
	".hg",
	".mypy_cache",
	".nox",
	".pants.d",
	".pytype",
	".ruff_cache",
	".svn",
	".tox",
	".venv",
	"__pypackages__",
	"_build",
	"buck-out",
	"build",
	"dist",
	"node_modules",
	"venv",
]

line-length = 160

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.8
target-version = "py38"

[lint.per-file-ignores]
"__init__.py" = ["F403"]
