# select = ["ALL"]
# select = [
# 	# imported from tinygrad
# 	"F",  # Pyflakes
# 	"W6",
# 	"E71",
# 	"E72",
# 	"E112",   # no-indented-block
# 	"E113",   # unexpected-indentation
# 	# "E124",
# 	"E203",   # whitespace-before-punctuation
# 	"E272",   # multiple-spaces-before-keyword
# 	"E275",   # missing-whitespace-after-keyword
# 	"E303",   # too-many-blank-lines
# 	"E304",   # blank-line-after-decorator
# 	"E501",   # line-too-long
# 	# "E502",
# 	"E702",   # multiple-statements-on-one-line-semicolon
# 	"E703",   # useless-semicolon
# 	"E731",   # lambda-assignment
# 	"W191",   # tab-indentation
# 	"W291",   # trailing-whitespace
# 	"W293",   # blank-line-with-whitespace
# 	"UP039",  # unnecessary-class-parentheses
# 	"C416",   # unnecessary-comprehension
# 	"RET506", # superfluous-else-raise
# 	"RET507", # superfluous-else-continue
# 	"A",      # builtin-variable-shadowing, builtin-argument-shadowing, builtin-attribute-shadowing
# 	"SIM105", # suppressible-exception
# 	"FURB110",# if-exp-instead-of-or-operator
# 	"RUF018", # assignment-in-assert
# ]

select = ["ALL"]
ignore = [
	"PD",
	"E501",
	"E701",
	"E702",
	"E741",
	"E401",
	"D100",
	"D101",
	"D102",
	"D103",
	"D105",
	"D107",
	"D203",
	"D211",
	"D212",
	"D213",
	"S101",
	"I001",
	"Q003",
	"T201",
	"PYI034",
	"W292",
	"TD002",
	"TD003",
	"PT018",
	"PT027",
	"ANN",
	"COM812",
	"PLR2004",
	"PLR0912",
	"PLR0913",
	"ERA001",
	"FBT001",
	"FBT002",
	"BLE001",
	"FIX002"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
	".bzr",
	".direnv",
	".eggs",
	".git",
	".git-rewrite",
	".hg",
	".mypy_cache",
	".nox",
	".pants.d",
	".pytype",
	".ruff_cache",
	".svn",
	".tox",
	".venv",
	"__pypackages__",
	"_build",
	"buck-out",
	"build",
	"dist",
	"node_modules",
	"venv",
]

line-length = 160

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.8
target-version = "py38"

[lint.per-file-ignores]
"__init__.py" = ["F403"]
