require "default.startup"
require "default.plugin"

require "default.indent-blankline"
require "default.autopairs"
require "default.comments"
require "default.gitsigns"
require "default.nvimtree"
require "default.treesitter"
require "default.nvim-yati"
require "default.cmp"
require "default.lsp"
require "default.navigator"

require "default.option"
require "default.keymap"
