version: 2
root-markers:
  - pyproject.toml
  - setup.py
  - setup.cfg
  - requirements.txt
  - ruff.toml
  - .ruff.toml
  - mypy.ini
  - .mypy.ini
  - .git/
lint-debounce: 200ms
tools:
  python-ruff: &python-ruff
    lint-command: "ruff check --config ${HOME}/.config/ruff/config.toml --quiet -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    lint-ignore-exit-code: true
    # format-command: "ruff check --config ${HOME}/.config/ruff/config.toml --fix --exit-zero --quiet -"
    # format-stdin: true
  python-mypy: &python-mypy
    lint-command: "mypy --show-column-numbers --config-file ${HOME}/.config/mypy/config.ini"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"
languages:
  python:
    - <<: *python-ruff
    - <<: *python-mypy
