version: 2
root-markers:
  - .git/
lint-debounce: 200ms
tools:
  python-ruff: &python-ruff
    lint-command: "ruff check --config ${HOME}/.config/ruff/config.toml --quiet -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    # format-command: "ruff check --fix --exit-zero --quiet -"
    # format-stdin: true
  python-mypy: &python-mypy
    lint-command: "mypy --show-column-numbers"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"
languages:
  python:
    - <<: *python-ruff
    - <<: *python-mypy
